function [Hd,N] = BLW_F(Fs)
%BLW_F Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.2 and the DSP System Toolbox 9.4.
% Generated on: 16-Nov-2019 18:31:00

% Equiripple Highpass filter designed using the FIRPM function.

% All frequency values are in Hz.


Fstop = 0.5;             % Stopband Frequency
Fpass = 1;               % Passband Frequency
Dstop = 0.31622776602;   % Stopband Attenuation
Dpass = 0.057501127785;  % Passband Ripple
dens  = 20;              % Density Factor

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fstop, Fpass]/(Fs/2), [0 1], [Dstop, Dpass]);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
Hd = dfilt.dffir(b);

% [EOF]
